/**
 * Decision Memory contracts -- DenkKern
 *
 * Source of truth: docs/sprints/sprint-6-backlog.md SS Schema
 * Owner: Orchestration layer (Amir)
 *
 * DecisionRecord is the immutable, durable record of:
 *   1. What the system knew at decision time  -- context_snapshot
 *   2. What the system recommended            -- recommendation_shown
 *   3. What the decision-maker chose          -- decision
 *   4. What happened after the decision       -- tracking -> outcome
 *
 * IMMUTABILITY RULES
 *   context_snapshot     -- written once; never overwritten.
 *   recommendation_shown -- written once; never overwritten.
 *   decision             -- written once; never overwritten.
 *   tracking             -- mutable via read -> patch -> write (DK-602, DK-604).
 *   outcome              -- mutable via read -> patch -> write (DK-604 sets OutcomeRecord).
 *   locked_at            -- null for Sprint 6 pilot.
 *                           Sprint 10: set to created_at once outcome is confirmed.
 */

// ---------------------------------------------------------------------------
// Outcome draft -- auto-generated by DK-603 from existing files.
// Not the final record; presented to the operator for confirmation in DK-604.
// ---------------------------------------------------------------------------

export interface OutcomeDraft {
  case_id: string;
  decision_id: string;              // DecisionRecord.id
  is_auto_generated: true;
  generated_at: string;             // ISO 8601

  // Arrival vs. prediction
  predicted_arrival_date: string;   // prediction.json eta.expected
  actual_arrival_date: string;      // arrival-event.json actual_arrival_date
  prediction_error_days: number;    // actual - predicted (negative = early)
  actual_delay_days: number;        // vs eta.baseline (arrival-event.json field)

  // Decision quality
  selected_scenario_id: string;     // DecisionRecord.decision.scenario_chosen
  recommended_scenario_id: string;  // DecisionRecord.recommendation_shown.top_recommendation
  followed_recommendation: boolean;

  // Financial impact
  wait_cost_eur: number;            // WAIT scenario estimated_cost_eur
  actual_cost_eur: number;          // selected scenario estimated_cost_eur
  estimated_cost_avoided_eur: number; // wait_cost - actual_cost

  // Production impact -- null = unknown at draft time; operator confirms in DK-604.
  production_impact_detected: boolean | null;

  // Narrative
  draft_summary: string;

  // Confirmation requirement
  requires_human_confirmation: true;
}

// ---------------------------------------------------------------------------
// Outcome record -- written by DK-604 after operator confirmation.
// Patched into DecisionRecord.outcome. null until confirmed.
// ---------------------------------------------------------------------------

export interface ProductionImpact {
  stopped: boolean;
  stopped_days: number | null;          // null if production was not interrupted
  customer_commitment_met: boolean;
}

export type DecisionQuality = 'EXCELLENT' | 'GOOD' | 'ACCEPTABLE' | 'POOR';

export type PredictionAccuracyAssessment =
  | 'ACCURATE'       // |error| <= 2 days
  | 'UNDERESTIMATED' // arrived later than predicted (delay worse than forecast)
  | 'OVERESTIMATED'  // arrived earlier than predicted (delay better than forecast)
  | null;            // not yet assessed

export interface OutcomeRecord {
  status: 'confirmed';

  confirmed_at: string;              // ISO 8601
  confirmed_by: string;              // user_id (e.g. "lena")
  confirmation_channel: string;      // e.g. "api", "ui"
  is_auto_generated: false;          // always false -- human confirmation required

  // Carried from outcome-draft.json (system-computed)
  actual_arrival_date: string;       // from arrival-event.json
  prediction_error_days: number;     // actual - predicted ETA
  actual_delay_days: number;         // vs eta.baseline

  // Human-confirmed or human-overridden
  actual_cost_eur: number;           // from draft or human override
  estimated_cost_avoided_eur: number; // recomputed if cost overridden; else from draft

  // Human-confirmed
  production_impact: ProductionImpact;
  decision_quality: DecisionQuality;

  // System-computed at confirmation time
  prediction_accuracy_assessment: PredictionAccuracyAssessment;

  notes: string | null;
}

// ---------------------------------------------------------------------------
// DecisionRecord -- the core Sprint 6 contract
// ---------------------------------------------------------------------------

export interface DecisionRecord {
  id: string;                          // UUIDv4 -- generated at write time
  case_id: string;
  schema_version: '1.0';
  created_at: string;                  // ISO 8601 -- timestamp of decision
  locked_at: null;                     // null: Sprint 6 pilot. Sprint 10: set to created_at.

  // Context snapshot (immutable)
  // Exactly what the system knew when the decision was made.
  // Source files: prediction.json, inventory-status.json, cost-model.json,
  //               disruption-context.json.
  context_snapshot: {
    predicted_delay_days: number;
    prediction_confidence: 'HIGH' | 'MEDIUM' | 'LOW';
    inventory_buffer_days: number;
    daily_downtime_cost_eur: number;
    daily_downtime_cost_source: string;
    route_profile: string;
    active_signal_count: number;
    dismissed_signal_count: number;
    highest_signal_severity: 'HIGH' | 'MEDIUM' | 'LOW' | 'NONE';
  };

  // Recommendation shown (immutable)
  // Exactly what the system showed the operator before they decided.
  recommendation_shown: {
    top_recommendation: string;
    recommendation_confidence: number;
    approval_required: boolean;
    approval_reason: string | null;
    ranked_scenarios: Array<{
      rank: number;
      scenario: string;
      estimated_cost_eur: number;
      risk_level: string;
    }>;
  };

  // Decision (immutable)
  decision: {
    scenario_chosen: string;
    followed_recommendation: boolean;
    decided_at: string;
    approved_by: string;
    notes: string | null;
  };

  // Tracking (mutable)
  // Updated by DK-602 (arrival data) and DK-604 (tracking_active -> false).
  tracking: {
    tracking_active: boolean;
    expected_arrival_date: string;
    actual_arrival_date: string | null;
    actual_delay_days: number | null;
  };

  // Outcome (mutable)
  // Written by DK-604. null until the operator confirms the outcome.
  outcome: OutcomeRecord | null;

  // Execution placeholder (Sprint 11 -- null for all Sprint 6 records)
  execution?: {
    status: 'not_started' | 'in_progress' | 'completed' | 'not_applicable';
    completed_at: string | null;
  } | null;

  // Fingerprint
  fingerprint: {
    delay_tier: 'SHORT' | 'MEDIUM' | 'LONG' | 'EXTREME';
    inventory_tier: 'CRITICAL' | 'LOW' | 'ADEQUATE' | 'COMFORTABLE';
    downtime_cost_tier: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
    scenario_type: string;
    followed_recommendation: boolean;
    region: string;
  };
}
