/**
 * Execution task contracts — DenkKern
 *
 * Source of truth: docs/architecture/06-data-contracts.md §9
 * Owner: Execution layer
 *
 * Generated by the orchestration layer on `execution_triggered`.
 * Free version: manual checklist.
 * Enterprise version: steps may be auto-advanced by workflow engine events.
 */

export type StepStatus = 'pending' | 'in_progress' | 'completed' | 'failed';
export type TaskStatus = 'not_started' | 'in_progress' | 'completed' | 'failed';

export interface ExecutionStep {
  step_id: string;
  label: string;                    // Human-readable action description
  status: StepStatus;
  updated_by?: string;              // user_id or "system"
  updated_at?: string;              // ISO 8601
  notes?: string;                   // Operator notes
}

export interface ExecutionTask {
  task_id: string;                  // UUID
  case_id: string;
  scenario_id: string;              // Which scenario was approved
  created_at: string;               // ISO 8601
  steps: ExecutionStep[];
  overall_status: TaskStatus;
}
