/**
 * GET /api/demo/shipments/:id/execution-validation
 *
 * Returns the Execution Validation screen data (Screen 8).
 * Includes the 6-item checklist, blocking vs non-blocking items,
 * and whether execution can proceed.
 *
 * All data derived from the canonical decision-engine-output.json.
 * The checklist is generated by the execution_planner agent trace step.
 */

import { NextRequest, NextResponse } from 'next/server';
import { readFileSync } from 'fs';
import { join, resolve } from 'path';

const MOCK_ROOT = process.env['MOCK_ROOT'] ?? resolve(process.cwd(), '..', '..');
const ENGINE_FILE = join(MOCK_ROOT, 'mock', 'cases', 'SH-2024-0042', 'decision-engine-output.json');

function loadEngine() {
  return JSON.parse(readFileSync(ENGINE_FILE, 'utf-8'));
}

interface RouteParams {
  params: { id: string };
}

export async function GET(
  _req: NextRequest,
  { params }: RouteParams
): Promise<NextResponse> {
  const { id } = params;

  try {
    const engine = loadEngine();

    if (id !== engine.meta.case_id) {
      return NextResponse.json(
        { error: `Case '${id}' not found in demo data.` },
        { status: 404 }
      );
    }

    const { execution_validation, recommendation, approval_routing } = engine.engine_output;
    const action = engine.actions.find(
      (a: { action_id: string }) => a.action_id === recommendation.action_id
    );

    const blocking = execution_validation.checklist.filter(
      (item: { item_id: string }) => execution_validation.blocking_items.includes(item.item_id)
    );
    const nonBlocking = execution_validation.checklist.filter(
      (item: { item_id: string }) => execution_validation.non_blocking_items.includes(item.item_id)
    );

    const completedCount = execution_validation.checklist.filter(
      (item: { status: string }) => item.status === 'confirmed'
    ).length;

    const response = {
      schema_version: engine.meta.schema_version,
      case_id: engine.meta.case_id,
      action_id: execution_validation.action_id,
      action_label: action.label,
      execution_can_proceed: execution_validation.execution_can_proceed,
      execution_cannot_proceed_reason: execution_validation.execution_cannot_proceed_reason,
      approval_status: approval_routing.approval_status,
      approval_required: approval_routing.approval_required,
      checklist: {
        total: execution_validation.checklist.length,
        completed: completedCount,
        blocking: blocking,
        non_blocking: nonBlocking,
      },
      booking_deadline: action.booking_deadline,
      estimated_arrival: action.estimated_arrival,
    };

    return NextResponse.json(response, { status: 200 });
  } catch (err) {
    console.error('[GET /api/demo/shipments/:id/execution-validation]', err);
    return NextResponse.json({ error: 'Failed to load execution validation data.' }, { status: 500 });
  }
}
